# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import information.crud.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(validators=[information.crud.models.age_limiter])),
                ('city', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
