# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='timestamp_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='timestamp_lastupdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
