# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20190626_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='timestamp_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='timestamp_lastupdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
